#!/usr/bin/env python3
"""Regenerate `src/requirements.txt` from `uv.lock` for SAM Lambda packaging.

`sam build` invokes pip with `requirements.txt` to install runtime dependencies
into the Lambda zip. The project's authoritative dependency source is
`pyproject.toml` + `uv.lock`, so we materialize a pinned, no-hashes
requirements.txt for the Python pip builder.

Run before `sam build` whenever pyproject.toml / uv.lock changes:
    uv run python scripts/sync-requirements.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "src" / "requirements.txt"


def main() -> int:
    uv = shutil.which("uv")
    if uv is None:
        print("error: 'uv' not found on PATH", file=sys.stderr)
        return 1
    proc = subprocess.run(
        [
            uv,
            "export",
            "--no-hashes",
            "--no-dev",
            "--no-emit-project",
            "--frozen",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        return proc.returncode
    TARGET.write_text(_strip_annotations(proc.stdout), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


def _strip_annotations(text: str) -> str:
    """Drop indented `# via ...` annotation lines emitted by newer uv versions.

    Older uv (<= 0.5.x) doesn't emit them; pinning the file to a uv-version-
    stable form keeps the drift-guard test deterministic across environments.
    Header comments at column 0 (e.g. `# This file was autogenerated...`) are
    preserved.
    """
    kept = [line for line in text.splitlines() if line[:1] not in (" ", "\t")]
    return "\n".join(kept) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
