"""Drift guard: src/requirements.txt must stay in sync with uv.lock.

`sam build` packages Lambda dependencies from `src/requirements.txt`. If a
contributor adds/upgrades a dep in pyproject.toml + uv.lock but forgets to
re-run `scripts/sync-requirements.py`, the Lambda zip would silently miss
the new package and crash with ImportError at runtime. This test fails the
build before that happens.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
REQUIREMENTS_PATH = ROOT / "src" / "requirements.txt"


def _has_uv() -> bool:
    return shutil.which("uv") is not None


@pytest.mark.skipif(not _has_uv(), reason="uv binary not available in this environment")
def test_requirements_txt_matches_uv_export() -> None:
    proc = subprocess.run(
        ["uv", "export", "--no-hashes", "--no-dev", "--no-emit-project", "--frozen"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    expected = proc.stdout
    actual = REQUIREMENTS_PATH.read_text(encoding="utf-8")
    # Normalize the autogenerated comment line that embeds an absolute path
    # (the `-o <abs path>` form differs between the dev machine and CI).
    expected_norm = _strip_command_comment(expected)
    actual_norm = _strip_command_comment(actual)
    assert actual_norm == expected_norm, (
        "src/requirements.txt is stale. Run: uv run python scripts/sync-requirements.py"
    )


def _strip_command_comment(text: str) -> str:
    """Drop the `#    uv export ...` line that embeds an absolute -o path."""
    return "\n".join(line for line in text.splitlines() if not line.startswith("#    uv export"))
